name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run code coverage (tarpaulin)
      run: cargo tarpaulin --ignore-tests --verbose
    - name: Run linting (clippy)
      run: cargo clippy -- -D warnings --verbose
    - name: Run formatting (fmt)
      run: cargo fmt -- --check --verbose
    - name: Run audit
      run: cargo audit --verbose
